local toast = require("epicenter.ui.toast")

describe("toast maths", function()
  it("draws a progress bar", function()
    expect.eq(toast.bar(0, 10, "#", "-"), "----------")
    expect.eq(toast.bar(1, 10, "#", "-"), "##########")
    expect.eq(toast.bar(0.5, 10, "#", "-"), "#####-----")
  end)

  it("clamps a bar fraction", function()
    expect.eq(toast.bar(-1, 4, "#", "-"), "----")
    expect.eq(toast.bar(2, 4, "#", "-"), "####")
    expect.eq(toast.bar(nil, 4, "#", "-"), "----")
  end)

  it("stacks upward from the bottom right", function()
    local boxes = toast.layout({ 1, 2 }, 100, 40, 20)
    expect.eq(#boxes, 2)
    expect.eq(boxes[2].col, 78, "flush to the right edge")
    expect.eq(boxes[1].col, 78)
    expect.eq(boxes[2].row, 36, "the newest toast sits lowest")
    expect.eq(boxes[1].row, 33, "older toasts stack above it, clear of its border")
    expect.truthy(boxes[1].row + boxes[1].height + 1 < boxes[2].row, "stacked toasts never overlap")
  end)

  it("never places a toast off screen", function()
    local boxes = toast.layout({ 5, 5, 5, 5, 5, 5, 5, 5 }, 30, 10, 20)
    for _, box in ipairs(boxes) do
      expect.truthy(box.row >= 0)
      expect.truthy(box.col >= 0)
    end
  end)
end)

describe("toast stack", function()
  before_each(function()
    require("epicenter.config").reset()
    toast.clear()
  end)

  after_each(function()
    toast.clear()
  end)

  it("shows and dismisses a notice", function()
    local handle = toast.notify("indexing finished", { level = "info", timeout = 60000 })
    expect.eq(toast.count(), 1)
    handle.dismiss()
    expect.eq(toast.count(), 0)
  end)

  it("keeps several notices stacked", function()
    toast.notify("one", { timeout = 60000 })
    toast.notify("two", { timeout = 60000 })
    expect.eq(toast.count(), 2)
    toast.clear()
    expect.eq(toast.count(), 0)
  end)

  it("auto-dismisses after the timeout", function()
    toast.notify("brief", { timeout = 10 })
    wait(function()
      return toast.count() == 0
    end, 2000, "auto dismiss")
  end)

  it("holds a progress toast open until it finishes", function()
    local p = toast.progress("building navgraph")
    expect.eq(toast.count(), 1)
    p.update(0.5, "compiling")
    expect.eq(toast.count(), 1)
    p.finish()
    expect.eq(toast.count(), 0)
  end)
end)
